- include_tasks: apt.yml

- name: copy environment-agnostic nginx config files
  register: nginx_agnostic_config
  copy:
    src: _env/nginx
    dest: /etc/
    owner: root
    group: root
    mode: '0644'

- name: copy environment-specific nginx config files
  register: nginx_specific_config
  copy:
    src: "{{ env }}/nginx"
    dest: /etc/
    owner: root
    group: root
    mode: '0644'

- name: Use new config
  when: nginx_agnostic_config.changed or nginx_specific_config.changed
  systemd:
    name: nginx
    state: reloaded

- name: Enable nginx at startup
  systemd:
    name: nginx
    enabled: yes
