- include_tasks: apt.yml

- name: nginx config files
  register: nginx_config
  copy:
    src: nginx
    dest: /etc/
    owner: root
    group: root
    mode: '0644'

- name: Use new config
  when: nginx_config.changed
  systemd:
    name: nginx
    state: reloaded

- name: Enable nginx at startup
  systemd:
    name: nginx
    enabled: yes
