#!/bin/bash

ERRORS_TO="peter@malaprop.org"
STAMP=`date '+%Y%m%d_%H%M%S'`
DATE=`date '+%Y%m%d'`
BACKUP_FILENAME="/tmp/database-$STAMP.sql.bz2"
WARNINGS_FILENAME="/tmp/database-warnings-$STAMP.log"

umask 177

/usr/sbin/logrotate /etc/logrotate.conf

/usr/bin/mysqldump \
  --defaults-extra-file=/root/backup.password.cnf \
  -u lobsters \
  --all-databases \
  --opt \
  --skip-add-drop-table \
  --allow-keywords \
  --comments \
  --compress \
  --dump-date \
  --force \
  --log-error=$WARNINGS_FILENAME \
  --routines \
  --single-transaction \
  --quick \
  --tz-utc \
  | nice -n 15 ionice -c 2 -n 7 bzip2 > $BACKUP_FILENAME

if [ -s $WARNINGS_FILENAME ]; then
  ERROR=`/bin/cat $WARNINGS_FILENAME`
  echo -e "Subject: Lobsters backup warnings\n\n$ERROR" | /usr/bin/sendmail $ERRORS_TO
fi

# database
/usr/bin/tarsnap -c -f "$(uname -n)-database-$STAMP" \
  $BACKUP_FILENAME \
  $WARNINGS_FILENAME

/bin/rm -f $BACKUP_FILENAME $WARNINGS_FILENAME

# logs and config files not in ansible repo
/usr/bin/tarsnap -c -f "$(uname -n)-logs-$STAMP" \
  /root/backup.password.cnf \
  /srv/lobste.rs/http/config/database.yml \
  /srv/lobste.rs/http/config/initializers/production.rb \
  /srv/lobste.rs/http/log/*$DATE* \
  /srv/lobste.rs/log/*$DATE* \
  /var/log/mysql/*$DATE* \
  /var/log/nginx/*$DATE* \
